export { default as Header } from './Header' 
export { default as NavBar } from './NavBar' 
export { default as Footer } from './Footer' 
export { default as FooterDetails } from './FooterDetails' 
export { default as SocialIcons } from './SocialIcons' 